/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPingtestRouteImport } from './routes/api/pingtest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingtestRoute = ApiPingtestRouteImport.update({
  id: '/api/pingtest',
  path: '/api/pingtest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/api/chat': typeof ApiChatRoute
  '/api/pingtest': typeof ApiPingtestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/api/chat': typeof ApiChatRoute
  '/api/pingtest': typeof ApiPingtestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/api/chat': typeof ApiChatRoute
  '/api/pingtest': typeof ApiPingtestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-assistant' | '/api/chat' | '/api/pingtest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-assistant' | '/api/chat' | '/api/pingtest'
  id: '__root__' | '/' | '/ai-assistant' | '/api/chat' | '/api/pingtest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPingtestRoute: typeof ApiPingtestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pingtest': {
      id: '/api/pingtest'
      path: '/api/pingtest'
      fullPath: '/api/pingtest'
      preLoaderRoute: typeof ApiPingtestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPingtestRoute: ApiPingtestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
